# -*- coding: utf-8 -*-
"""07_validacion_modelo_QUBO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vf84Sxn5AbovDvUc9D_w4DeUyPtJukUr
"""

# -*- coding: utf-8 -*-
# ==============================================================================
# CELDA: ANÁLISIS DE ESTABILIDAD NUMÉRICA
# ==============================================================================
import os
import time
import numpy as np
import pandas as pd
import cvxpy as cp
import matplotlib.pyplot as plt
from sklearn.preprocessing import KBinsDiscretizer, PolynomialFeatures
from sklearn.metrics import mean_squared_error, r2_score
import gc

# ------------------------------------------------------------------------------
# 1. CONFIGURACIÓN DE CARPETA
# ------------------------------------------------------------------------------
carpeta_salida = "resultados"
os.makedirs(carpeta_salida, exist_ok=True)
print(f"Directorio seguro de salida preparado en: {carpeta_salida}")

# ------------------------------------------------------------------------------
# 2. CARGA EXACTA DE TUS DATOS
# ------------------------------------------------------------------------------
print("\nCargando y procesando los datos originales...")

ruta_csv = "muestreo_de_puntos_SOBOL.csv"
with open("semilla.txt", "r") as f:
    semilla_guardada = int(f.read().strip())

nuevos_nombres = [f'x{i}' for i in range(1, 11)] + ['fun']

# Procesar datos por fragmentos
x_mins = np.full(10, np.inf)
x_maxs = np.full(10, -np.inf)
y_min_global = np.inf
y_max_global = -np.inf
y_sum_global = 0.0
total_filas = 0
sample_y = []

for chunk in pd.read_csv(ruta_csv, chunksize=50000):
    chunk = chunk.sample(frac=0.8, random_state=semilla_guardada)
    if len(chunk.columns) == 11:
        chunk.columns = nuevos_nombres
    chunk = chunk.dropna()
    total_filas += len(chunk)

    y_vals = chunk['fun'].values
    y_min_global = min(y_min_global, y_vals.min())
    y_max_global = max(y_max_global, y_vals.max())
    y_sum_global += y_vals.sum()

    sample_y.append(y_vals[::100])

    X_chunk = chunk[nuevos_nombres[:10]].values
    x_mins = np.minimum(x_mins, X_chunk.min(axis=0))
    x_maxs = np.maximum(x_maxs, X_chunk.max(axis=0))

percentil_10 = np.percentile(np.concatenate(sample_y), 10)
y_mean_global = y_sum_global / total_filas
y_range_original = y_max_global - y_min_global
if y_range_original == 0: y_range_original = 1

total_puntos = total_filas
print(f"Total de datos cargados (100%): {total_puntos} puntos.")
del sample_y

# ------------------------------------------------------------------------------
# 3. FUNCIÓN MODULAR DE ENTRENAMIENTO Y EVALUACIÓN
# ------------------------------------------------------------------------------
def evaluar_fraccion(frac):
    """
    Entrena el modelo usando una fracción de los datos,
    y evalúa su error contra la totalidad de los datos (la función física real).
    """
    # Escalar Y basado en estadísticas globales
    y_min = y_min_global
    y_range = y_range_original
    pesos_valor_alto = 1.0
    pesos_valor_bajo = 1.0

    # Discretización (usando tu misma lógica)
    X_train_dummy = None
    prim = [f'x{i}' for i in range(1, 6)]
    ult = [f'x{i}' for i in range(6, 11)]

    disc_p = KBinsDiscretizer(n_bins=17, encode='onehot-dense', strategy='uniform')
    disc_u = KBinsDiscretizer(n_bins=15, encode='onehot-dense', strategy='uniform')
    disc_p.fit(np.vstack([x_mins[:5], x_maxs[:5]]))
    disc_u.fit(np.vstack([x_mins[5:], x_maxs[5:]]))

    num_binarias = 5*17 + 5*15
    nombres_binarias_sk = [f'x{i}' for i in range(num_binarias)]
    poly = PolynomialFeatures(degree=2, include_bias=True)
    poly.fit(np.zeros((1, num_binarias)))

    d = poly.n_output_features_
    A = np.zeros((d, d))
    b_vec = np.zeros(d)
    lambda_reg = 1.0

    # Entrenamiento con CVXPY por lotes
    semilla_aleatoria = 42
    for chunk in pd.read_csv(ruta_csv, chunksize=50000):
        chunk = chunk.sample(frac=0.8, random_state=semilla_guardada)
        if frac < 1.0:
            chunk = chunk.sample(frac=frac, random_state=semilla_aleatoria)
        if len(chunk.columns) == 11:
            chunk.columns = nuevos_nombres
        chunk = chunk.dropna()
        if len(chunk) == 0:
            continue

        y_train = chunk['fun'].values
        y_train_scaled = (y_train - y_min) / y_range
        pesos = np.where(y_train <= percentil_10, pesos_valor_alto, pesos_valor_bajo)

        X_chunk = chunk[prim + ult]
        Xb_primeras = disc_p.transform(X_chunk[prim])
        Xb_ultimas = disc_u.transform(X_chunk[ult])
        X_binarias = np.hstack([Xb_primeras, Xb_ultimas])
        X_poly = poly.transform(X_binarias)

        X_poly_w = X_poly * pesos[:, None]
        A += X_poly.T @ X_poly_w
        b_vec += X_poly.T @ (pesos * y_train_scaled)

        del X_poly_w, X_poly, Xb_primeras, Xb_ultimas, X_binarias, X_chunk
        gc.collect()

    A = (A + A.T) / 2.0
    coefs = cp.Variable(d)
    objective = cp.Minimize(cp.quad_form(coefs, cp.psd_wrap(A)) - 2 * b_vec @ coefs + lambda_reg * cp.sum_squares(coefs))
    prob = cp.Problem(objective)
    prob.solve(solver=cp.OSQP, verbose=False)
    c_val = coefs.value

    # Evaluación cruzada contra el dataset del 100% por lotes
    sse = 0.0
    sst = 0.0
    n_total = 0

    for chunk in pd.read_csv(ruta_csv, chunksize=50000):
        chunk = chunk.sample(frac=0.8, random_state=semilla_guardada)
        if len(chunk.columns) == 11:
            chunk.columns = nuevos_nombres
        chunk = chunk.dropna()

        y_eval = chunk['fun'].values
        X_eval = chunk[prim + ult]

        Xb_p = disc_p.transform(X_eval[prim])
        Xb_u = disc_u.transform(X_eval[ult])
        X_bin_eval = np.hstack([Xb_p, Xb_u])
        X_poly_eval = poly.transform(X_bin_eval)

        y_pred_scaled = X_poly_eval @ c_val
        y_pred = (y_pred_scaled * y_range) + y_min

        sse += np.sum((y_eval - y_pred) ** 2)
        sst += np.sum((y_eval - y_mean_global) ** 2)
        n_total += len(y_eval)

        del X_poly_eval, X_bin_eval, Xb_p, Xb_u
        gc.collect()

    rmse = np.sqrt(sse / n_total)
    r2 = 1 - (sse / sst) if sst!= 0 else 0.0

    return rmse, r2

# ------------------------------------------------------------------------------
# 4. BUCLE DE ESTABILIDAD (Del 10% al 100%)
# ------------------------------------------------------------------------------
fracciones = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
resultados = []

print("\nIniciando Análisis de Convergencia Muestral. Esto puede tomar tiempo...")
print("-" * 65)
print(f"{'Porcentaje':<12} | {'Puntos Usados':<15} | {'RMSE (Costo)':<15} | {'R2 Score':<10}")
print("-" * 65)

tiempo_inicio = time.time()

for frac in fracciones:
    # Evaluar la fracción contra el 100% de la información
    rmse, r2 = evaluar_fraccion(frac)

    resultados.append({
        'Fraccion': frac * 100,
        'N_Puntos': int(total_puntos * frac),
        'RMSE': rmse,
        'R2': r2
    })

    print(f"{frac*100:>10.0f} % | {int(total_puntos * frac):>13} | {rmse:>13.2f} | {r2:>9.4f}")

tiempo_fin = time.time()
print("-" * 65)
print(f"Análisis completado en {(tiempo_fin - tiempo_inicio)/60:.2f} minutos.")

# Convertir a DataFrame para guardado fácil
df_resultados = pd.DataFrame(resultados)
ruta_csv_out = os.path.join(carpeta_salida, 'resultados_estabilidad_sobol.csv')
df_resultados.to_csv(ruta_csv_out, index=False)

# ------------------------------------------------------------------------------
# 5. CREACIÓN DE LA GRÁFICA
# ------------------------------------------------------------------------------
# Configuración visual
plt.style.use('default')
fig, ax1 = plt.subplots(figsize=(10, 6))

color_rmse = '#d9534f' # Rojo
color_r2 = '#5bc0de' # Azul suave

# Eje Principal: RMSE (Error)
ax1.set_xlabel('Número de Puntos Muestreados (N)', fontsize=12, fontweight='bold')
ax1.set_ylabel('Error Cuadrático Medio (RMSE)', color=color_rmse, fontsize=12, fontweight='bold')
line1 = ax1.plot(df_resultados['N_Puntos'], df_resultados['RMSE'],
                 marker='o', linestyle='-', linewidth=2, color=color_rmse, label='RMSE (Error)')
ax1.tick_params(axis='y', labelcolor=color_rmse)
ax1.grid(True, linestyle='--', alpha=0.6)

# Eje Secundario: R2 (Precisión)
ax2 = ax1.twinx()
ax2.set_ylabel('Coeficiente de Determinación ($R^2$)', color='#2b547e', fontsize=12, fontweight='bold')
line2 = ax2.plot(df_resultados['N_Puntos'], df_resultados['R2'],
                 marker='s', linestyle='--', linewidth=2, color=color_r2, label='Precisión $R^2$')
ax2.tick_params(axis='y', labelcolor='#2b547e')

# Títulos y Leyendas
lines = line1 + line2
labels = [l.get_label() for l in lines]
ax1.legend(lines, labels, loc='center right', fontsize=11, frameon=True, shadow=True)

plt.title('Análisis de Estabilidad y Convergencia del Muestreo (Sobol vs Modelo QUBO)',
          fontsize=14, fontweight='bold', pad=15)

# Zona de asintota (Sombra verde para mostrar la estabilidad)
puntos_80_porciento = df_resultados['N_Puntos'].iloc[-3] # A partir del 80%
ax1.axvspan(puntos_80_porciento, total_puntos, color='green', alpha=0.1, label='Zona de Estabilidad')
ax1.text(puntos_80_porciento + (total_puntos-puntos_80_porciento)/2,
         df_resultados['RMSE'].max() * 0.9, 'Convergencia\nEstabilizada',
         horizontalalignment='center', color='darkgreen', fontweight='bold')

plt.tight_layout()

# Guardar la figura
ruta_grafica = os.path.join(carpeta_salida, 'Convergencia_Estabilidad_Sobol.png')
plt.savefig(ruta_grafica, dpi=300, bbox_inches='tight')

print(f"\n¡Éxito! Gráfica y datos exportados en:\n{carpeta_salida}")
plt.show()

# ==============================================================================
# CÁLCULO DE CORRELACIÓN DE SPEARMAN USANDO EL MODELO YA ENTRENADO Y EL "RESTO" DE DATOS
# ==============================================================================
import pickle
import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error, r2_score
from scipy.stats import spearmanr
import gc

# 1. Rutas a los archivos
ruta_csv = "muestreo_de_puntos_SOBOL.csv"
ruta_modelo = "modelo_10D_entrenado_.pkl"

nuevos_nombres = [f'x{i}' for i in range(1, 11)] + ['fun']

print("\nCargando la semilla del entrenamiento...")
try:
    with open("semilla.txt", "r") as f:
        semilla_guardada = int(f.read().strip())
    print(f"Semilla recuperada: {semilla_guardada}")
except FileNotFoundError:
    raise ValueError("No se encontró 'semilla.txt'. Asegúrate de correr el Código '06_ajuste_regresion_ridge.py' primero en esta misma carpeta.")

# ==============================================================================
# 2. CARGAR EL MODELO YA ENTRENADO
# ==============================================================================
print("\nCargando el modelo.pkl ya entrenado...")
with open(ruta_modelo, 'rb') as f:
    modelo_info = pickle.load(f)

disc_p = modelo_info['discretizer_primeras']
disc_u = modelo_info['discretizer_ultimas']
y_min_original = modelo_info['y_min']
y_range_original = modelo_info['y_range']
intercept = modelo_info['intercept']
coefs = modelo_info['coefs']

coeficientes_completos = np.concatenate(([intercept], coefs))

# ==============================================================================
# 3. PREDECIR SOBRE "EL RESTO" (VALIDACIÓN)
# ==============================================================================
print("\nReconstruyendo el espacio de validación y prediciendo...")

prim = [f'x{i}' for i in range(1, 6)]
ult = [f'x{i}' for i in range(6, 11)]

poly = PolynomialFeatures(degree=2, include_bias=True)
first_fit = True

# Usaremos listas para almacenar los resultados y concatenarlos al final (más seguro para memoria)
y_val_real_list = []
y_pred_real_list = []

total_val_rows = 0

# ATENCIÓN: El chunksize DEBE ser 50000 para replicar el comportamiento del Código '06_ajuste_regresion_ridge.py'
for chunk in pd.read_csv(ruta_csv, chunksize=50000, low_memory=False):
    if len(chunk.columns) == 11:
        chunk.columns = nuevos_nombres
    chunk = chunk.dropna()

    # -------------------------------------------------------------------
    # ESTA ES PARA QUE LOS DATOS TENGAN EL RIGOR SOBRE '06_ajuste_regresion_ridge.py'
    # -------------------------------------------------------------------
    train_chunk = chunk.sample(frac=0.8, random_state=semilla_guardada)
    val_chunk = chunk.drop(train_chunk.index) # <- Este es tu verdadero 20%
    # -------------------------------------------------------------------

    if len(val_chunk) > 0:
        y_chunk_real = val_chunk['fun'].values
        X_val = val_chunk.drop('fun', axis=1)

        # Discretizar
        X_bin_batch = np.hstack([disc_p.transform(X_val[prim]), disc_u.transform(X_val[ult])])

        # Polinomio
        if first_fit:
            X_poly_batch = poly.fit_transform(X_bin_batch)
            first_fit = False
        else:
            X_poly_batch = poly.transform(X_bin_batch)

        # Predecir
        y_pred_scaled_batch = X_poly_batch @ coeficientes_completos
        y_pred_batch = (y_pred_scaled_batch * y_range_original) + y_min_original

        # Guardar resultados
        y_val_real_list.append(y_chunk_real)
        y_pred_real_list.append(y_pred_batch)
        total_val_rows += len(y_chunk_real)

    # Limpiar RAM
    del chunk, train_chunk, val_chunk, X_bin_batch, X_poly_batch
    gc.collect()

print(f"-> Predicciones completadas. Puntos validados: {total_val_rows}")

# Unir todas las listas en arrays de numpy
y_val_real = np.concatenate(y_val_real_list)
y_pred_real = np.concatenate(y_pred_real_list)
del y_val_real_list, y_pred_real_list
gc.collect()

# ==============================================================================
# 4. CÁLCULO DE MÉTRICAS FINALES Y SPEARMAN
# ==============================================================================
print("\nCalculando métricas de divergencia y correlación de Spearman...")

rmse_val = np.sqrt(mean_squared_error(y_val_real, y_pred_real))
r2_val = r2_score(y_val_real, y_pred_real)

# Submuestreo para Spearman si hay demasiados datos
if len(y_val_real) > 5_000_000:
    print("Muestra grande detectada: Submuestreando para cálculo de Spearman...")
    idx = np.random.RandomState(42).choice(len(y_val_real), 5_000_000, replace=False)
    rho_s, p_value = spearmanr(y_val_real[idx], y_pred_real[idx])
else:
    rho_s, p_value = spearmanr(y_val_real, y_pred_real)

print("\n======================================================================")
print(" RESULTADOS FINALES SOBRE EL CONJUNTO DE VALIDACIÓN ('EL RESTO')")
print("======================================================================")
print(f"RMSE (Error) sobre datos nuevos : {rmse_val:.4f} kg")
print(f"R^2 (Precisión)                 : {r2_val:.4f}")
print(f"Rho_S (Correlación de Spearman) : {rho_s:.4f}")
print(f"P-Value de Spearman             : {p_value:.2e}")
print("======================================================================")
print(f"\n>>> EL DATO A ASIGNAR:")
print(f"\\rho_{{\\text{{S}}}} = {rho_s:.4f}")